package com.bifrost3d.core.graphics;

public enum ETextureFilter {

    MIN_MAG_NEAREST,
    MIN_NEAREST_MAG_LINEAR,
    MIN_LINEAR_MAG_NEAREST,
    MIN_MAG_LINEAR,

    MIN_MAG_MIP_NEAREST,
    MIN_MAG_NEAREST_MIP_LINEAR,
    MIN_NEAREST_MAG_LINEAR_MIP_NEAREST,
    MIN_NEAREST_MAG_MIP_LINEAR,

    MIN_LINEAR_MAG_MIP_NEAREST,
    MIN_LINEAR_MAG_NEAREST_MIP_LINEAR,
    MIN_MAG_LINEAR_MIP_NEAREST,
    MIN_MAG_MIP_LINEAR,

    ANISOTROPIC,

}
